version: "3.9"
services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    environment:
     - NODE_ENV=development

  nginx:
    image: nginx:1.23
    ports:
     - 8000:80
    volumes:
     - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
