version: "3.9"
services:
  backend:
    container_name: backend
    build: backend/
    ports:
      - "127.0.0.1:8080:80"
    volumes:
     - "/var/run/docker.sock:/var/run/docker.sock"  # Allow container access to the daemon/engine API.
     - "./backend:/app"
  frontend:
    container_name: frontend
    build: frontend/
    depends_on:
      - backend
    ports:
     - "127.0.0.1:3000:3000"
    volumes:
     - "./frontend:/app"
     - ".frontend/node_modules:/app/node_modules"
    environment:
     - NODE_ENV=development
     - CHOKIDAR_USEPOLLING=true

  nginx:
    container_name: reverseproxy
    image: nginx:1.23
    ports:
     - 80:80
    volumes:
     - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend
